spring:
   application:
      name: Task2_SchoolApp
   datasource: 
      driverClassName: org.postgresql.Driver
      url: "jdbc:postgresql://localhost:5432/school_app"
      password: "abc123"
      username: "postgres"
      testOnBorrow: true
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      max-active: 15
      max-idle: 10
      max-wait: 8000
flyway:
   url: jdbc:postgresql://localhost:5432/school_app
   schemas: public
   user: "postgres"
   password: "abc123"
